<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PossibleNextFlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Mariusz Madanowski
 */
class PossibleNextFlagRepository extends EntityRepository
{

}
